[package]
name = "rs-cpurenderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
fltk = "1.3.33"

[dependencies]
image = "0.24.5"